# Generated by Django 6.0.2 on 2026-02-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_alter_student_image_alter_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='number',
            new_name='phone_number',
        ),
    ]
