# Generated by Django 6.0.2 on 2026-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_rename_number_student_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='iamge',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
