# Generated by Django 6.0.2 on 2026-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0004_remove_event_iamge_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
